---
title: "Lab 4"
author: "Joseph Kabariti"
date: "October 7, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
```

Code from lab:
Standardize
```{r}
standardize1 = function(a, centered_only = TRUE) {

  avg = mean(a)
  st.d = sd(a)
  if (centered_only){
      return(a-avg)
  }
  else{
    return((a-avg)/st.d)
  }
}


standardize1(c(1,2,3,4), centered_only=FALSE)

standardize1(c(1,2,3,4), centered_only=TRUE)

standardize2 = function(a, na.rm= FALSE) {
  if(na.rm){
    a1 = subset(a,a!='NA')
  }
  else {
    a1 = a
  }
  avg = mean(a1)
  st.d = sd(a1)
  return((a-avg)/st.d)
}

standardize2(c(1,2,3,4,NA),na.rm=TRUE)

standardize2(c(1,2,NA,3,4,NA))
```


Sum of elements
```{r}
sum_of_elements = function(a) {
  overall_sum = 0
  for(i in 1:nrow(a)) {
    for (j in 1:ncol(a)){
      overall_sum = overall_sum + a[i,j]
    }
  }
  return(overall_sum)
}

a = matrix(1:20,nrow=5,byrow=FALSE)

sum_of_elements(a)

sum(a)
```





```{r}
data = data.frame(x=c(-4,7))
ah_lim = c(-3.5,3.5)
n_lim = c(-0.25,6.5)
g = ggplot(data = data,aes(x=x)) + scale_x_discrete(limits=c(-0.25,3.5),labels=c("theta_0","theta_a")) + stat_function(aes(color="Type I Error"),xlim=ah_lim,fun=dnorm, n= 101,args = list(mean = 0, sd = 1)) + stat_function(fill="blue",xlim=c(1.6,3.5),fun=dnorm, n= 101,args = list(mean = 0, sd = 1),geom="area") + geom_vline(xintercept = 1.6,linetype="dashed") + stat_function(aes(color="Type II Error"),xlim=n_lim,fun=dnorm, n= 101,args = list(mean = 3.2, sd = 1)) + stat_function(fill="red",xlim=c(-0.25,1.6),fun=dnorm, n= 101,args = list(mean = 3.2, sd = 1),geom="area") + scale_color_manual(values=c("blue","red")) + annotate(geom="text",label=expression(beta),x=1.25,y=0.025,color="blue") + annotate(geom="text",label=expression(alpha),x=1.95,y=0.025,color="white")

plot(g)
```


```{r}
isprime = function(x)
{test = TRUE
  for(i in seq(x-2)+1){
    if((x %% i) == 0)
    {test = FALSE}
  }
return(test)
}

isprime(89)
```

